name: Scrape TCG Data

on:
  schedule:
    - cron: '0 18 * * *' # 2:00 AM HKT (18:00 UTC)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' # Run only on dev branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev # Explicitly check out dev branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Use Python 3.10 for better compatibility

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          if ! command -v chromium-browser &> /dev/null; then
            echo "Chromium installation failed"
            exit 1
          fi

      - name: Debug Chromium installation
        run: |
          apt-cache policy chromium-browser
          which chromium-browser
          ls -l /usr/bin/chromium-browser || echo "Chromium not found in /usr/bin"
          ls -l /usr/lib/chromium-browser || echo "Chromium not found in /usr/lib"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the scraper script
        run: |
          python pipeline_tcg_scraper.py

      - name: Commit and push CSV files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/ptcg/*.csv data/opcg/*.csv
          git diff-index --quiet HEAD || (git commit -m "Add daily TCG data CSVs" --allow-empty)
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}